[package]
name = "rustcv"
version = "0.1.0"
authors = ["Ben Zhang <benzh@cs.berkeley.edu>"]

[dependencies]
bitflags = "1.0"
failure = "0.1"
num-derive = "0.2"
num-traits = "0.2"
opencv-sys = { path = "opencv-sys" }

[workspace]
members = ["opencv-sys"]
